import { Home } from './home';

export const HOMES: Home[] = [
  {
    id: 1,
    name: 'The Americano',
    front: '../../../assets/images/homes/site-built/Americano/Front.jpg',
    back: '../../../assets/images/homes/site-built/Americano/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Americano/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Americano/Front.jpg','../../../assets/images/homes/site-built/Americano/Back.jpg'],
    squarefeet: 2130,
    stories: 1,
    beds: 4,
    baths: 3,
    garage: 3,
    bonus: 'Two master suites!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 2,
    name: 'The Arapahoe',
    front: '../../../assets/images/homes/site-built/Arapahoe/Front.jpg',
    back: '../../../assets/images/homes/site-built/Arapahoe/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Arapahoe/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Arapahoe/Front.jpg','../../../assets/images/homes/site-built/Arapahoe/Back.jpg'],
    squarefeet: 2493,
    stories: 1,
    beds: 3,
    baths: 2.5,
    garage: 2,
    bonus: 'Oversized garage!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 3,
    name: 'The Bishop',
    front: '../../../assets/images/homes/site-built/Bishop/Front.jpg',
    back: '../../../assets/images/homes/site-built/Bishop/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Bishop/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Bishop/Front.jpg','../../../assets/images/homes/site-built/Bishop/Back.jpg'],
    squarefeet: 2801,
    stories: 2,
    beds: 4,
    baths: 3.5,
    garage: 2,
    bonus: 'Oversized garage and optional 420sf bonus room!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 4,
    name: 'The Cafe',
    front: '../../../assets/images/homes/site-built/Cafe/Front.jpg',
    back: '../../../assets/images/homes/site-built/Cafe/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Cafe/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Cafe/Front.jpg','../../../assets/images/homes/site-built/Cafe/Back.jpg'],
    squarefeet: 1834,
    stories: 1,
    beds: 3,
    baths: 2,
    garage: 3,
    bonus: 'RV garage!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 5,
    name: 'The Espresso',
    front: '../../../assets/images/homes/site-built/Espresso/Front.jpg',
    back: '../../../assets/images/homes/site-built/Espresso/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Espresso/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Espresso/Front.jpg','../../../assets/images/homes/site-built/Espresso/Back.jpg'],
    squarefeet: 1529,
    stories: 1,
    beds: 3,
    baths: 2,
    garage: 2,
    bonus: '',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 6,
    name: 'The Ferguson',
    front: '../../../assets/images/homes/site-built/Ferguson/Front.jpg',
    back: '../../../assets/images/homes/site-built/Ferguson/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Ferguson/Floorplan.jpg','../../../assets/images/homes/site-built/Ferguson/Floorplan2.jpg'],
    images: ['../../../assets/images/homes/site-built/Ferguson/Front.jpg','../../../assets/images/homes/site-built/Ferguson/Back.jpg'],
    squarefeet: 2532,
    stories: 2,
    beds: 3,
    baths: 2.5,
    garage: 2,
    bonus: 'Oversized garage!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 7,
    name: 'The Hoover',
    front: '../../../assets/images/homes/site-built/Hoover/Front.jpg',
    back: '../../../assets/images/homes/site-built/Hoover/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Hoover/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Hoover/Front.jpg','../../../assets/images/homes/site-built/Hoover/Back.jpg'],
    squarefeet: 1624,
    stories: 1,
    beds: 3,
    baths: 2,
    garage: 2,
    bonus: '',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 8,
    name: 'The Humboldt',
    front: '../../../assets/images/homes/site-built/Humboldt/Front.jpg',
    back: '../../../assets/images/homes/site-built/Humboldt/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Humboldt/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Humboldt/Front.jpg','../../../assets/images/homes/site-built/Humboldt/Back.jpg'],
    squarefeet: 1878,
    stories: 1,
    beds: 3,
    baths: 2,
    garage: 2,
    bonus: 'Oversized garage!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 9,
    name: 'The Jefferson',
    front: '../../../assets/images/homes/site-built/Jefferson/Front.jpg',
    back: '../../../assets/images/homes/site-built/Jefferson/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Jefferson/Floorplan.jpg','../../../assets/images/homes/site-built/Jefferson/Floorplan2.jpg'],
    images: ['../../../assets/images/homes/site-built/Jefferson/Front.jpg','../../../assets/images/homes/site-built/Jefferson/Back.jpg'],
    squarefeet: 2151,
    stories: 2,
    beds: 3,
    baths: 2.5,
    garage: 3,
    bonus: '',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'JL Home Design'
  },
  {
    id: 10,
    name: 'The Northbrook',
    front: '../../../assets/images/homes/site-built/Northbrook/Front.jpg',
    back: '../../../assets/images/homes/site-built/Northbrook/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Northbrook/Floorplan.jpg','../../../assets/images/homes/site-built/Northbrook/Floorplan2.jpg'],
    images: ['../../../assets/images/homes/site-built/Northbrook/Front.jpg','../../../assets/images/homes/site-built/Northbrook/Back.jpg'],
    squarefeet: 2513,
    stories: 2,
    beds: 4,
    baths: 2.5,
    garage: 2,
    bonus: 'Optional 440sf bonus room!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 11,
    name: 'The Vasquez',
    front: '../../../assets/images/homes/site-built/Vasquez/Front.jpg',
    back: '../../../assets/images/homes/site-built/Vasquez/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Vasquez/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Vasquez/Front.jpg','../../../assets/images/homes/site-built/Vasquez/Back.jpg'],
    squarefeet: 2301,
    stories: 2,
    beds: 3,
    baths: 3.5,
    garage: 3,
    bonus: 'Optional 355sf bonus room!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  },
  {
    id: 12,
    name: 'The Wilson',
    front: '../../../assets/images/homes/site-built/Wilson/Front.jpg',
    back: '../../../assets/images/homes/site-built/Wilson/Back.jpg',
    floorplan: ['../../../assets/images/homes/site-built/Wilson/Floorplan.jpg'],
    images: ['../../../assets/images/homes/site-built/Wilson/Front.jpg','../../../assets/images/homes/site-built/Wilson/Back.jpg'],
    squarefeet: 3156,
    stories: 2,
    beds: 3,
    baths: 2.5,
    garage: 3,
    bonus: 'Optional 644sf bonus room!',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    copy: 'Alan Mascord Design Associates, Inc.'
  }
]
